export const INDICATOR_LIMIT_VALUES = 89 + 1;
export const CANDLE_LIMIT_VALUES = Math.max(144, INDICATOR_LIMIT_VALUES + INDICATOR_LIMIT_VALUES + 1);
export const CANDLES_PACKET_SIZE = 64;

export const CANDLE_UPDATE_TIMEOUT = 59000; // mSec
export const TICKER_UPDATE_TIMEOUT = 15000; // mSec
